"""changed table to examinee

Revision ID: 1145ed83b305
Revises: 280f09db00ac
Create Date: 2020-06-05 14:52:53.295051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1145ed83b305'
down_revision = '280f09db00ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examinee', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinee', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
