"""empty message

Revision ID: 280f09db00ac
Revises: e3bfccf55c19
Create Date: 2020-06-04 17:05:15.236986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280f09db00ac'
down_revision = 'e3bfccf55c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinee', sa.Column('attendace', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examinee', 'attendace')
    # ### end Alembic commands ###
