"""added daily passsword table

Revision ID: 4289f083de84
Revises: f166b7abbbb1
Create Date: 2020-06-19 21:53:10.253578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4289f083de84'
down_revision = 'f166b7abbbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailypass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailypass')
    # ### end Alembic commands ###
