"""empty message

Revision ID: 46bba187ab7b
Revises: 8681a8d4fd51
Create Date: 2020-06-04 16:15:15.820961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bba187ab7b'
down_revision = '8681a8d4fd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinee', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'examinee', ['name'])
    op.drop_column('examinee', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinee', sa.Column('image', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'examinee', type_='unique')
    op.drop_column('examinee', 'name')
    # ### end Alembic commands ###
