"""changed table

Revision ID: e538b20c6777
Revises: 7e250a6e02bc
Create Date: 2020-05-23 21:52:17.692159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e538b20c6777'
down_revision = '7e250a6e02bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('RollNumber', sa.String(length=64), nullable=True))
    op.add_column('table', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_table_RollNumber'), 'table', ['RollNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_RollNumber'), table_name='table')
    op.drop_column('table', 'image')
    op.drop_column('table', 'RollNumber')
    # ### end Alembic commands ###
