"""empty message

Revision ID: ed556a2d2f33
Revises: a444b2f02f30
Create Date: 2020-06-05 18:37:04.586762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed556a2d2f33'
down_revision = 'a444b2f02f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_examinee_databasename', table_name='examinee')
    op.create_index(op.f('ix_examinee_databasename'), 'examinee', ['databasename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examinee_databasename'), table_name='examinee')
    op.create_index('ix_examinee_databasename', 'examinee', ['databasename'], unique=1)
    # ### end Alembic commands ###
