"""added image

Revision ID: f4fda1a54f82
Revises: 96287a474766
Create Date: 2020-06-04 16:02:06.352426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fda1a54f82'
down_revision = '96287a474766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinee', sa.Column('filename', sa.String(length=128), nullable=True))
    op.add_column('examinee', sa.Column('name', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'examinee', ['name'])
    op.drop_column('examinee', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinee', sa.Column('image', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'examinee', type_='unique')
    op.drop_column('examinee', 'name')
    op.drop_column('examinee', 'filename')
    # ### end Alembic commands ###
